services:
  database-blog:
    image: mysql:9.1.0
    container_name: database-blog
    restart: unless-stopped
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: app-blog
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - '5400:3306'
    networks:
      - blog_network

  app-blog:
    container_name: app-blog
    restart: unless-stopped
    build:
      context: .
      dockerfile: docker/apache/Dockerfile
    ports:
      - '9000:80'
    volumes:
      - ./src:/var/www/html
    depends_on: 
      - database-blog
    networks:
      - blog_network

networks:
  blog_network:
    driver: bridge

volumes:
  mysql_data: